name: Feature branch workflow

on:
  push:
    branches-ignore:
      - master

jobs:
  build-and-test:
    name: Build code and run tests.
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        ghc-version:
          - "8.10"
          - "9.0"
          - "latest"
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc-version }}
          enable-stack: true
      - run: stack build --test --bench --no-run-tests --no-run-benchmarks
      - run: stack test --verbosity warn
